import FormAuthorization from '@/components/FormAuthorization/FormAuthorization';
import { baseUrl, rootMetadata } from '@/constants/common.constants';
import { Metadata } from 'next/types';

export const metadata: Metadata = {
  ...rootMetadata,
  title: 'Code Craft - Login',
  openGraph: {
    url: `${baseUrl}signin`,
    images: [
      'https://firebasestorage.googleapis.com/v0/b/code-craft-app.appspot.com/o/images%2Flog.jpg?alt=media&token=7f6061b8-c5f1-4558-b968-3a622926077e',
    ],
    title: 'Code Craft',
    description: 'Platform for posting articles on various topicsGenerated by create next app',
  },
};

const SignIn = async (): Promise<JSX.Element> => <FormAuthorization registration={false} />;

export default SignIn;
