import { Metadata } from 'next/types';
import { baseUrl, rootMetadata } from '@/constants/common.constants';
import Image from 'next/image';
import { IconBrandFacebook, IconBrandTwitter, IconBrandLinkedin } from '@tabler/icons-react';
import { amatic } from '@/app/layout';
import banner from '@/assets/contacts.png';
import styles from './contacts.page.module.scss';

export const metadata: Metadata = {
  ...rootMetadata,
  title: 'Code Craft - Contacts',
  openGraph: {
    url: `${baseUrl}contacts`,
    images: [
      'https://firebasestorage.googleapis.com/v0/b/code-craft-app.appspot.com/o/images%2Flog.jpg?alt=media&token=7f6061b8-c5f1-4558-b968-3a622926077e',
    ],
    title: 'Code Craft',
    description: 'Platform for posting articles on various topicsGenerated by create next app',
  },
};

const ContactsPage = (): JSX.Element => (
  <div className={styles.contacts}>
    <div>
      <p>We are happy to help you with any question.</p>
      <p>Contact us!</p>
    </div>
    <div className={styles.contactItem}>
      <p className={styles.title}>EMAIL</p>
      <p className={`${styles.email} ${amatic.className}`}>code-craft-app@gmail.com</p>
    </div>
    <div className={styles.contactItem}>
      <p className={styles.title}>SOCIAL</p>
      <div className={styles.social}>
        <IconBrandTwitter size="3rem" strokeWidth="1.2" />
        <IconBrandFacebook size="3rem" strokeWidth="1.2" />
        <IconBrandLinkedin size="3rem" strokeWidth="1.2" />
      </div>
    </div>
  </div>
);

export default ContactsPage;
