import Header from '@/layout/Header/Header';
import { Inter  } from 'next/font/google';
import './globals.scss';
import { Session, getServerSession } from 'next-auth';
import ProviderToolkit from '@/redux/provider';
import styles from './layout.module.scss';
import NextAuthProvider from './providers';
import { authOptions } from './api/auth/[...nextauth]/route';
import RootStyleRegistry from './emotion';

const montserrat = Inter ({ subsets: ['latin'] });

export const metadata = {
  title: 'Code Craft',
  description: 'Platform for posting articles on various topicsGenerated by create next app',
  keywords: 'blog, programming',
  template: '%s',
};

export const getSession = async (): Promise<Session | null> => {
  const session = await getServerSession(authOptions);
  return session
}

export default async function RootLayout({ children }: { children: React.ReactNode }): Promise<JSX.Element> {
  const session = await getSession();
  return (
    <html lang="en"className={styles.html}>
      <NextAuthProvider>
        <RootStyleRegistry>
          <ProviderToolkit>
            <body className={`${styles.body} ${montserrat.className}`}>
              <Header session={session} />
              <main className={styles.main}>
                {children}
              </main>
            </body>
          </ProviderToolkit> 
        </RootStyleRegistry>
      </NextAuthProvider>
    </html>
  );
}
