import Header from '@/layout/Header/Header';
import { Montserrat } from 'next/font/google';
import './globals.scss';
import { GetServerSideProps } from 'next';
import { Session, getServerSession } from 'next-auth';
import NextAuthProvider from './providers';
import { authOptions } from './api/auth/[...nextauth]/route';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Code Craft',
  description: 'Platform for posting articles on various topicsGenerated by create next app',
  keywords: 'blog, programming',
  template: '%s',
};

export const getSession = async (): Promise<Session | null> => {
  const session = await getServerSession(authOptions);
  return session
}

export default async function RootLayout({ children }: { children: React.ReactNode }): Promise<JSX.Element> {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NextAuthProvider>
          <Header session={session} />
          <main>
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
