import AllPostsList from '@/components/AllPosts/AllPostsList/PostsList';
import Aside from '@/components/Aside/Aside';
import GreetingSection from '@/components/GreetingSection/GreetingSection';
import { Metadata } from 'next';
import styles from './home.module.scss';

export const metadata: Metadata = {
  title: 'Code Craft',
  description: 'Platform for posting articles on various topicsGenerated by create next app',
  keywords: 'blog, programming',
  // template: '%s',
};

const Home = async (): Promise<JSX.Element> => (
  <>
    <GreetingSection />
    <div className={styles.postsContainer}>
      <AllPostsList />
      <Aside />
    </div>
  </>
);

export default Home;
