import FormAuthorization from '@/components/FormAuthorization/FormAuthorization';
import { Session, getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';
import { baseUrl, rootMetadata } from '@/constants/common.constants';
import { Metadata } from 'next/types';
import { authOptions } from '../api/auth/[...nextauth]/route';

export const checkSession = async (): Promise<Session | null> => {
  const session = await getServerSession(authOptions);
  return session;
};

export const metadata: Metadata = {
  ...rootMetadata,
  title: 'Code Craft - Login',
  openGraph: {
    url: `${baseUrl}signup`,
    images: [
      'https://firebasestorage.googleapis.com/v0/b/code-craft-app.appspot.com/o/images%2Flog.jpg?alt=media&token=7f6061b8-c5f1-4558-b968-3a622926077e',
    ],
    title: 'Code Craft',
    description: 'Platform for posting articles on various topicsGenerated by create next app',
  },
};

const SignUp = async (): Promise<JSX.Element> => {
  const session = await checkSession();

  if (session) {
    redirect('/');
  }

  return <FormAuthorization registration={true} />;
};

export default SignUp;
